include:
  - .gitlab-ci-test.yml
  - .gitlab-ci-deploy.yml 

image: registry.gitlab.com/linumlabs/molecule-alpha/build/node-env:latest

# Cache modules in between jobs for current branch
cache:
  #key: ${CI_COMMIT_REF_SLUG}
  untracked: true
  paths:
    - node_modules/
    - ./*/node_modules/
    - Blockchain/node_modules/
    - ApiServer/node_modules/
    - WebApp/node_modules/
    - apt-cache/

variables:
  MOLECULE_FRONTEND_CONTAINER_IMAGE: registry.gitlab.com/linumlabs/molecule-alpha/testing/molecule-frontend:$CI_BUILD_REF_NAME
  MOLECULE_FRONTEND_CONTAINER_RELEASE_IMAGE: registry.gitlab.com/linumlabs/molecule-alpha/release/molecule-frontend:$CI_BUILD_REF_NAME
  MOLECULE_BACKEND_CONTAINER_IMAGE: registry.gitlab.com/linumlabs/molecule-alpha/testing/molecule-backend:$CI_BUILD_REF_NAME
  MOLECULE_BACKEND_CONTAINER_RELEASE_IMAGE: registry.gitlab.com/linumlabs/molecule-alpha/release/molecule-backend:$CI_BUILD_REF_NAME
  API_HOST: alpha-api-$CI_BUILD_REF_NAME.mol.ai/api
  GIT_SUBMODULE_STRATEGY: recursive
  # DOCKER_HOST: tcp://localhost:2375/
  NODE_OPTIONS: --max-old-space-size=4096
  TOOL_NODE_FLAGS: --max-old-space-size=4096

stages:
  - build
  - test
  - merge
  - docker-build
  - push
  - deploy
