include:
  - .gitlab-ci-test.yml
  - .gitlab-ci-deploy.yml 

# Cache modules in between jobs for current branch
cache:
  #key: ${CI_COMMIT_REF_SLUG}
  untracked: true
  paths:
    - node_modules/
    - ./*/node_modules/
    - Blockchain/node_modules/
    - ApiServer/node_modules/
    - WebApp/node_modules/
    - apt-cache/

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # DOCKER_HOST: tcp://localhost:2375/
  NODE_OPTIONS: --max-old-space-size=4096
  TOOL_NODE_FLAGS: --max-old-space-size=4096
  REGISTRY: 540682145059.dkr.ecr.us-west-2.amazonaws.com

image: $REGISTRY/linumlabs/molecule-alpha/build/node-env:latest

stages:
  - build
  - test
  - merge
  - docker-build
  - push
  - deploy
