# If build passes tests, push to release CR
docker-build:
  stage: docker-build
  image: yodascholtz/nix-build-env:latest
  services:
    - docker:dind
  variables:
    PROJECT_NAME: $CI_PROJECT_NAME
    BRANCH_NAME: $CI_BUILD_REF_NAME
  before_script:
    - echo "Starting Docker build stage..."
    - echo "Override global 'before_script'"
  script:
    - .environments/deployment/build.sh
  only:
    - nightly

deploy:
  stage: deploy
  environment: production
  image: yodascholtz/nix-build-env:latest
  variables:
    CLUSTER: AmazonEKS_LinumLabs_Spot
    PROJECT_NAME: $CI_PROJECT_NAME
    BRANCH_NAME: $CI_BUILD_REF_NAME
  before_script:
    - echo "Starting deploy stage..."
    - echo "Override global 'before_script'"
  script:
    - nix-shell .environments/shell.nix
    - .environments/scripts/configure-k8s.sh
    - .environments/deployment/deploy.sh
  only:
    - nightly
